#preprocessing parameters
#provide channel name for dapi and fish image
dapi_ch: 405
fish_ch: 561
camera_bg: 150
rolling_ball_radius: 15
#segmentation parameters
size_scale: 8
nuc_diameter: 25
#microscope paramaters
voxel_size_xy: 65
voxel_size_z: 200
#enter lens NA, RI of oil (or mounting medium?). Ex/Em of the dye (not the filter, right?)
NA: 1.45
RI: 1.518
Ex: 548
Em: 563
microscope: confocal
#Big Fish parameters
#cluster radius, (in nm) for spots to be considered a cluster.
foci_radius: 2000
#min number of RNAs to form a cluster
nb_in_foci: 5
#max value for plotting images. Recommend to set as 2X single RNA intensity.
vmax: 800
